# Generated by Django 5.0.14 on 2026-03-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin to top of project list'),
        ),
    ]
